complete -c dotfiles --no-files -d "Configure your ~/.dotfiles in your editor"
complete -c dotfiles --no-files -a "remove" -d "Run ~/.dotfiles/setup/remove.sh"
complete -c dotfiles --no-files -a "setup" -d "Run ~/.dotfiles/setup/install.sh"
complete -c dotfiles --no-files -a "user" -d "Open ~/.usershell in your editor"
complete -c dotfiles --no-files -a "git" -d "Open your gitconfigs in your editor"
complete -c dotfiles --no-files -a "bash" -d "Open your bash configs in your editor"
complete -c dotfiles --no-files -a "fish" -d "Open your fish configs in your editor"
complete -c dotfiles --no-files -a "zsh" -d "Open your zsh configs in your editor"
complete -c dotfiles --no-files -a "prezto" -d "Open your prezto configs in your editor"
